### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by RicardoZhy1215** [LChenGit/OMP_serial_dataset#1]
Hi, Le ! Many thanks for your contribution for parallel community! Do you plan to open source this dataset?

**Comment by thelechen** [comment]
Sure. We will release it this week. Sorry for the delay. We had too much going on.

**Comment by RicardoZhy1215** [comment]
Thanks for your quick reply!

**Comment by thelechen** [comment]
Hi @RicardoZhy1215 ,


I am sorry for the delay. I am busy with a recent deadline. Please find the dataset in the repo.  We are also open to collaboration. Thank you!
